version: '1.0.{build}'
environment:
  matrix:
    - nodejs_version: '9'
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
  - cmd: choco install sonarcube-scanner
install:
before_build:
  - cmd: npm install
build_script:
  - cmd: npm run build
clone_depth: 1
test_script:
  - cmd: sonar-scanner -Dsonar.projectKey=config-interface -Dsonar.organization=wk-j-github -Dsonar.sources=src -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=940f6517a5a823b166a31a9173557dedbdbc9401
deploy: off